name: Create release

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: release type
        required: true
        default: 'release'
        options:
          - prerelease
          - release
jobs:
  run-release:
    name: Run release
    runs-on: ubuntu-latest
    steps:
      - name: Fetch from origin repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Bump Version
        id: bumpVersion
        uses: ./.github/actions/bump-version
        with:
          releaseType: ${{ inputs.mode }}
          writeFile: true

      - name: Update Changelog
        run: conventional-changelog -p angular -i CHANGELOG.md -s

      - name: Commit Changes
        run: |
          git add .
          git commit -m "chore(release): release v${{ steps.bumpVersion.outputs.newVersion }} [ci skip]"
          git tag v${{ steps.bumpVersion.outputs.newVersion }}
          git push origin --tags
      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          generateReleaseNotes: true
          prerelease: ${{ inputs.mode == 'prerelease' }}
          tag: v${{ steps.bumpVersion.outputs.newVersion }}

      - run: git status
        shell: bash

