name: Create release

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: release type
        required: true
        default: 'release'
        options:
          - prerelease
          - release
jobs:
  run-release:
    name: Run release
    runs-on: ubuntu-latest
    steps:
      - name: Fetch from origin repo
        uses: actions/checkout@v3

      - name: Fetch
        run: |
          git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
          git fetch

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Bump Version
        id: bumpVersion
        uses: ./.github/actions/bump-version
        with:
          releaseType: release
          writeFile: true
      - run: git status
        shell: bash

