name: Create release

on:
  workflow_dispatch:

jobs:
  run-release:
    name: Run release
    runs-on: ubuntu-latest
    if: ${{ contains(github.head_ref, 'main') }}
    steps:
      - name: Fetch from origin repo
        uses: actions/checkout@v3

      - name: Fetch
        run: |
          git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
          git fetch

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Bump Version
        id: bumpVersion
        uses: ./.github/actions/bump-version
        with:
          releaseType: release
          writeFile: true

      - name: Tag and push
        run: |
          git add .
          git commit -m "chore: release v${{ steps.bumpVersion.newVersion }} [ci skip]" --no-verify
          git tag -a v${{ steps.bumpVersion.outputs.newVersion }} -m "chore: release ${{ steps.bumpVersion.newVersion }} [ci skip]"
          git push origin ${{ github.head_ref }}
          git push origin --tags
          echo ::set-output name=new_version::$(git describe HEAD --abbrev=0)
