on:
  push:
    branches:
      - main
jobs:
  one_run:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
  install:
    runs-on: ubuntu-latest
    name: Dependency installation
    needs: one_run
    steps:
      - uses: actions/checkout@v3
      - name: Yarn setup and dependency installation
        uses: ./.github/actions/nodejs
  bump:
    runs-on: ubuntu-latest
    name: Bump version
    needs: install
    steps:
      - uses: actions/checkout@v3

      - name: Fetch
        run: |
          git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
          git fetch
      - name: Yarn setup
        uses: ./.github/actions/nodejs
      - name: Bump version
        uses: ./.github/actions/bump-version
        id: bumpVersion
        with:
          releaseType: prerelease
      - name: Checking Bump result
        run: echo ${{ steps.bumpVersion.newVersion }}
