name: Update version on main

on:
  workflow_call:

jobs:
  mainUpdate:
    name: Update Version on main
    needs: run-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GHACTIONS }}

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Bump Version
        id: bumpVersion
        uses: ./.github/actions/bump-version
        with:
          isPrerelease: false
          writeFile: true

      - name: Update Changelog
        run: npx conventional-changelog-cli -p angular -i CHANGELOG.md -s

      - uses: ./.github/actions/set-up-git
        name: Set up git user
        with:
          name: ${{ secrets.GH_NAME }}
          email: ${{ secrets.GH_EMAIL }}

      - name: Commit Changes
        run: |
          git add .
          git commit -m "chore(release): release v${{ steps.bumpVersion.outputs.newVersion }} [ci skip]" --no-verify
          git push
